version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: car_rental_mongo
    ports:
      - "27018:27017"  # Changed to port 27018
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: car_rental_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: car_rental_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongodb_data: