export const EVENT_TYPES = {
  USER_CREATED: 'USER_CREATED',
  CAR_CREATED: 'CAR_CREATED', 
  CAR_UPDATED: 'CAR_UPDATED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED'
};