export const EVENT_TYPES = {
  USER_CREATED: 'USER_CREATED',
  CAR_CREATED: 'CAR_CREATED', 
  CAR_UPDATED: 'CAR_UPDATED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED', 
  BOOKING_FAILED: 'BOOKING_FAILED',
    /** Emitted when car availability is requested (Booking → Car) */
  CAR_AVAILABILITY_REQUEST: 'CAR_AVAILABILITY_REQUEST',
  /** Emitted when car availability response is sent (Car → Booking) */
  CAR_AVAILABILITY_RESULT: 'CAR_AVAILABILITY_RESULT',
};