export const EVENT_TYPES = {
  USER_CREATED: 'USER_CREATED',
  CAR_CREATED: 'CAR_CREATED', 
  CAR_UPDATED: 'CAR_UPDATED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED', 
  BOOKING_FAILED: 'BOOKING_FAILED',
  CAR_AVAILABILITY_REQUEST: 'CAR_AVAILABILITY_REQUEST',
  CAR_AVAILABILITY_RESULT: 'CAR_AVAILABILITY_RESULT',
  SEND_EMAIL: 'SEND_EMAIL',
  SEND_REMINDER: 'SEND_REMINDER'
};

export const EXCHANGES = {
  BOOKING: 'booking_events',
  CAR: 'car_events',
  NOTIFICATION: 'notification_events',
  USER: 'user_events'
};